### ISSUE TITLE
Is fabric analytics still set up for Daycation?

### ISSUE THREAD

**Issue by ryanbranciforte** [trailheadlabs/daycation-ios#21]
After months of up and down, I've noticed a steady decline of monthly active users for the past few weeks, with not a single day of increase in weeks. It is quite possible that reflects reality, but I wanted to check and confirm, for a few reasons:

1. Intertwine and partners initiated a huge outreach push to increase engagement and that has corresponded with a steady decline. 

2. Intertwine, partners and funders are using these analytics to help them determine their next steps. So I want to confirm we are actually tracking these stats accurately.

**Comment by ryanbranciforte** [comment]
![screen shot 2017-08-21 at 9 41 11 am](https://user-images.githubusercontent.com/2602563/29529656-6b284e18-8655-11e7-8df3-0cfd487c1d0b.png)

**Comment by nateirwin** [comment]
Nothing's changed with Fabric or Daycation and it looks like events are still getting pushed to Fabric successfully.
